UDD/UDD.Web/Controllers/AuthController.cs
using Microsoft.AspNet.Identity;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Security.Claims;
using System.Web;
using System.Web.Mvc;
using UDD.DataAccess.Model;
using UDD.Web.Models;

namespace UDD.Web.Controllers
{
    public class AuthController : Controller
    {
        private BooksDBEntities db = new BooksDBEntities();

        // GET: Auth
        [HttpGet]
        [AllowAnonymous]
        public ActionResult Login(string returnUrl)
        {
            ViewBag.returnUrl = returnUrl;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Login(LoginModel model, string returnUrl)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            var user = db.User.FirstOrDefault(u => u.Username == model.Username);
            if(user == null)
            {
                ModelState.AddModelError("", "User does not exist.");
                return View();
            }
            if(user.Password != model.Password)
            {
                ModelState.AddModelError("", "The password is not correct.");
                return View();
            }

            var identity = CreateUserIdentity(user);
            SignIn(identity);

            return RedirectToLocal(returnUrl);
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Logout()
        {
            SignOut();
            return RedirectToAction("Index", "Books");
        }

        // GET: Auth
        [HttpGet]
        public ActionResult ResetPassword()
        {
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult ResetPassword(ResetPasswordModel model)
        {
            if (!ModelState.IsValid)
            {
                return View();
            }

            if (model.PasswordFirstInput != model.PasswordSecondInput)
            {
                ModelState.AddModelError("", "Passwords don't match.");
                return View();
            }

            var user = db.User.Find(Convert.ToInt32(User.Identity.GetUserId()));
            user.Password = model.PasswordFirstInput;
            db.Entry(user).State = EntityState.Modified;
            db.SaveChanges();
            SignOut();
            return RedirectToAction("Info", "Home", new { message = "Password successfully changed. Please log in again." });
        }

        // GET: Auth
        [HttpGet]
        [AllowAnonymous]
        public ActionResult Register()
        {
            var categorySelectList = new List<SelectListItem>();
            var categories = db.Category;
            foreach (var category in categories)
            {
                var selectItem = new SelectListItem
                {
                    Text = category.Name,
                    Value = category.Id.ToString()
                };
                categorySelectList.Add(selectItem);
            }
            var defaultSelectItem = new SelectListItem
            {
                Text = "",
                Value = null
            };
            categorySelectList.Insert(0, defaultSelectItem);

            ViewBag.CategoryId = categorySelectList;
            return View();
        }

        [HttpPost]
        [AllowAnonymous]
        [ValidateAntiForgeryToken]
        public ActionResult Register(User user)
        {
            user.RoleId = 2;

            if (ModelState.IsValid)
            {
                db.User.Add(user);
                db.SaveChanges();
                return RedirectToAction("Info", "Home", new { message = "Registration was successful. Please log in." });
            }

            return RedirectToAction("Info", "Home", new { message = "Registration was not successful. Please proceed to login." });
        }

        private ActionResult RedirectToLocal(string returnUrl)
        {
            if (Url.IsLocalUrl(returnUrl))
            {
                return Redirect(returnUrl);
            }
            return RedirectToAction("Index", "Books");
        }

        private ClaimsIdentity CreateUserIdentity(User user)
        {
            var identity = new ClaimsIdentity(DefaultAuthenticationTypes.ApplicationCookie);
            identity.AddClaim(new Claim(ClaimTypes.Name, user.Username));
            identity.AddClaim(new Claim(ClaimTypes.Role, user.Role.Name));
            identity.AddClaim(new Claim(ClaimTypes.NameIdentifier, user.Id.ToString()));

            var subscribedCategory = user.CategoryId == null ? "All" : user.CategoryId.ToString();
            identity.AddClaim(new Claim("bookCategory", subscribedCategory));

            return identity;
        }

        private void SignIn(ClaimsIdentity identity)
        {
            var ctx = Request.GetOwinContext();
            var authManager = ctx.Authentication;

            authManager.SignIn(identity);
        }

        private void SignOut()
        {
            var ctx = Request.GetOwinContext();
            var authManager = ctx.Authentication;

            authManager.SignOut();
        }
    }
}

UDD/UDD.Web/Controllers/BooksController.cs
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web.Mvc;
using PdfSharp.Pdf.IO;
using TikaOnDotNet.TextExtraction;
using UDD.DataAccess.Model;
using UDD.Web.Models;
using UDD.Web.Sevices;
using Path = System.IO.Path;
using Nest;
using System.Security.Claims;
using UDD.Web.Helpers;
using System;
using Microsoft.AspNet.Identity;

namespace UDD.Web.Controllers
{
    public class BooksController : Controller
    {
        private BooksDBEntities db = new BooksDBEntities();
        private AccessControlHelper _accessControlHelper = new AccessControlHelper();

        // GET: Books
        [AllowAnonymous]
        public ActionResult Index()
        {
            var userIdentity = User.Identity as ClaimsIdentity;
            var books = db.Book.Include(c => c.Category).Include(u => u.User);
            if (User.Identity.IsAuthenticated)
            {
                foreach (var book in books)
                {
                    book.CanBeDownloaded = _accessControlHelper.BookCanBeDownloaded(book.CategoryId, userIdentity);
                }
            }
            return View(books.ToList());
        }

        // GET: Books/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Book.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // GET: Books/Create
        public ActionResult Create()
        {
            ViewBag.CategoryId = new SelectList(db.Category, "Id", "Name");
            ViewBag.LanguageId = new SelectList(db.Language, "Id", "Name");
            ViewBag.UserId = new SelectList(db.User, "Id", "FirstName");
            return View();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,CategoryId,LanguageId,UserId,Title,FileName,Author,Keywords,PublicationYear,MIME")] Book book)
        {
            if (ModelState.IsValid)
            {
                book.UserId = Convert.ToInt32(User.Identity.GetUserId());
                db.Book.Add(book);
                db.SaveChanges();
                book.Language = db.Language.First(l => l.Id == book.LanguageId);
                var bookPath = Path.Combine(Server.MapPath("~/UploadedBooks"), book.FileName);
                UpdateBookMetadata(book, bookPath);
                IndexBook(book, bookPath);
                return RedirectToAction("Index");
            }

            ViewBag.CategoryId = new SelectList(db.Category, "Id", "Name", book.CategoryId);
            ViewBag.LanguageId = new SelectList(db.Language, "Id", "Name", book.LanguageId);
            ViewBag.UserId = new SelectList(db.User, "Id", "FirstName", book.UserId);
            return View(book);
        }

        private void UpdateBookMetadata(Book book, string bookPath)
        {
            var document = PdfReader.Open(bookPath);
            document.Info.Title = book.Title;
            document.Info.Author = book.Author;
            document.Info.Keywords = book.Keywords;
            document.Save(bookPath);
        }

        private void IndexBook(Book book, string bookPath)
        {
            var textExtractor = new TextExtractor();
            var result = textExtractor.Extract(bookPath);

            var pdfBook = new PdfBook
            {
                Content = result.Text,
                Title = book.Title,
                Author = book.Author,
                Language = book.Language.Name,
                Id = book.Id,
                Keywords = book.Keywords
            };

            ElasticSearchService.Instance.Client.Index(pdfBook);
        }

        // GET: Books/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Book.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            ViewBag.CategoryId = new SelectList(db.Category, "Id", "Name", book.CategoryId);
            ViewBag.LanguageId = new SelectList(db.Language, "Id", "Name", book.LanguageId);
            ViewBag.UserId = new SelectList(db.User, "Id", "FirstName", book.UserId);
            return View(book);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,CategoryId,LanguageId,UserId,Title,FileName,Author,Keywords,PublicationYear,MIME")] Book book)
        {
            if (ModelState.IsValid)
            {
                book.UserId = Convert.ToInt32(User.Identity.GetUserId());
                db.Entry(book).State = EntityState.Modified;
                db.SaveChanges();
                book.Language = db.Language.First(l => l.Id == book.LanguageId);
                var bookPath = Path.Combine(Server.MapPath("~/UploadedBooks"), book.FileName);
                UpdateBookMetadata(book, bookPath);
                IndexBook(book, bookPath);
                return RedirectToAction("Index");
            }
            ViewBag.CategoryId = new SelectList(db.Category, "Id", "Name", book.CategoryId);
            ViewBag.LanguageId = new SelectList(db.Language, "Id", "Name", book.LanguageId);
            ViewBag.UserId = new SelectList(db.User, "Id", "FirstName", book.UserId);
            return View(book);
        }

        // GET: Books/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Book book = db.Book.Find(id);
            if (book == null)
            {
                return HttpNotFound();
            }
            return View(book);
        }

        // POST: Books/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Book book = db.Book.Find(id);
            db.Book.Remove(book);
            db.SaveChanges();
            ElasticSearchService.Instance.Client.Delete(new DeleteRequest<PdfBook>(id));
            return RedirectToAction("Index");
        }

        public FileResult Download(string filename)
        {
            var fileBytes = System.IO.File.ReadAllBytes(System.IO.Path.Combine(Server.MapPath("~/UploadedBooks"), filename));
            return File(fileBytes, System.Net.Mime.MediaTypeNames.Application.Octet, filename);
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

UDD/UDD.Web/Controllers/UploadController.cs
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Microsoft.Ajax.Utilities;
using PdfSharp.Pdf;
using PdfSharp.Pdf.IO;

namespace UDD.Web.Controllers
{
    public class UploadController : Controller
    {
        // GET: Upload
        public ActionResult UploadFile(HttpPostedFileBase upload)
        {
            if (Request.Files.Count > 0)
            {
                try
                {
                    var files = Request.Files;
                    var file = files[0];
                    string fileName;

                    if (Request.Browser.Browser.ToUpper() == "IE" || Request.Browser.Browser.ToUpper() == "INTERNETEXPLORER")
                    {
                        var testFiles = file.FileName.Split('\\');
                        fileName = testFiles[testFiles.Length - 1];
                    }
                    else
                    {
                        fileName = file.FileName;
                    }
                    var path = Path.Combine(Server.MapPath("~/UploadedBooks"), fileName);
                    var contentType = file.ContentType;

                    file.SaveAs(path);

                    var document = PdfReader.Open(path);
                    var title = document.Info.Title;
                    var autor = document.Info.Author;
                    var keywords = document.Info.Keywords;

                    return Json(new {Title = title, FileName = fileName, MIME = contentType, Author = autor, Keywords = keywords }, JsonRequestBehavior.AllowGet);
                }
                catch (Exception ex)
                {
                    return Json("Error occurred. Error details: " + ex.Message);
                }
            }
            return Json("No files selected");
        }
    }
}

UDD/UDD.Web/Views/Books/Create.cshtml
@model UDD.DataAccess.Model.Book

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

<div class="form-horizontal">
    <h4>Book</h4>
    <hr />

    @using (Html.BeginForm("UploadFile", "Upload", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {

        @Html.AntiForgeryToken()

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FileName, "File", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input id="input-id" type="file" data-show-preview="false" data-allowed-file-extensions='["pdf"]' class="form-control">
                @Html.ValidationMessageFor(model => model.FileName, "", new { @class = "text-danger" })
            </div>
        </div>
    }

    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        <div class="form-group">
            @Html.LabelFor(model => model.CategoryId, "Category", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                <input type="hidden" id="tboxFileName" name="FileName" />
                <input type="hidden" id="tboxMIME" name="MIME" />
                @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.LanguageId, "Language", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("LanguageId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.LanguageId, "", new { @class = "text-danger" })
            </div>
        </div>

        @*<div class="form-group">
            @Html.LabelFor(model => model.UserId, "Uploaded By", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
            </div>
        </div>*@

        <div class="form-group">
            @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", id = "tboxTitle" } })
                @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control", id = "tboxAuthor" } })
                @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Keywords, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Keywords, new { htmlAttributes = new { @class = "form-control", id = "tboxKeywords" } })
                @Html.ValidationMessageFor(model => model.Keywords, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.PublicationYear, "Publication Year", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.PublicationYear, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.PublicationYear, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </div>
    }

</div>

    <div>
    @Html.ActionLink("Back to List", "Index")
</div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.5/js/plugins/piexif.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.5/js/plugins/sortable.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.5/js/plugins/purify.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.5/js/fileinput.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.5/js/locales/LANG.js"></script>

    <script>
        $(document)
            .ready(function () {

                $("#input-id")
                    .fileinput({
                        uploadUrl: "/Upload/UploadFile"
                    })
                    .on('fileuploaded',
                    function (event, data) {
                        console.log(data.response);

                        $("#tboxTitle").val(data.response.Title);
                        $("#tboxFileName").val(data.response.FileName);
                        $("#tboxMIME").val(data.response.MIME);
                        $("#tboxAuthor").val(data.response.Author);
                        $("#tboxKeywords").val(data.response.Keywords);
                    });

                $('.file-caption-main').css("display", "block");
                $('.file-caption').css("max-width", "280px");
                $('.file-input').css("max-width", "601px");
            });
    </script>

}

UDD/UDD.Web/Views/Books/Details.cshtml
@model UDD.DataAccess.Model.Book

@{
    ViewBag.Title = "Details";
}

<h2>Details</h2>

<div>
    <h4>Book</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Title)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Title)
        </dd>

        <dt>
            File Name
        </dt>

        <dd>
            @Html.DisplayFor(model => model.FileName)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Author)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Author)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Keywords)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Keywords)
        </dd>

        <dt>
            Publication Year
        </dt>

        <dd>
            @Html.DisplayFor(model => model.PublicationYear)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.MIME)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.MIME)
        </dd>

        <dt>
            Category
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Category.Name)
        </dd>

        <dt>
            Language
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Language.Name)
        </dd>

        <dt>
            Uploaded by
        </dt>

        <dd>
            @Html.DisplayFor(model => model.User.FirstName)
        </dd>

    </dl>
</div>
<p>
    @if (User.IsInRole("Admin"))
    {
    <span>@Html.ActionLink("Edit", "Edit", new { id = Model.Id }) |</span>
    }
    @Html.ActionLink("Back to List", "Index")
</p>

UDD/UDD.Web/Views/Books/Edit.cshtml
@model UDD.DataAccess.Model.Book

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

<div class="form-horizontal">
    <h4>Book</h4>
    <hr />

    @using (Html.BeginForm("UploadFile", "Upload", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {

        @Html.AntiForgeryToken()

        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.FileName, "New File", htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                <input id="input-id" type="file" data-show-preview="false" data-allowed-file-extensions='["pdf"]' accept="application/pdf" class="form-control">
                @Html.ValidationMessageFor(model => model.FileName, "", new { @class = "text-danger" })
            </div>
        </div>
    }


    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()

        @*<div class="form-horizontal">
            <h4>Book</h4>
            <hr />*@
            @Html.ValidationSummary(true, "", new { @class = "text-danger" })
            @Html.HiddenFor(model => model.Id)

            <div class="form-group">
                @Html.LabelFor(model => model.FileName, "File Name", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.FileName, new { htmlAttributes = new { @class = "form-control", @readonly = "readonly", id = "tboxFileName" } })
                    @Html.ValidationMessageFor(model => model.FileName, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.CategoryId, "Category", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("CategoryId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.CategoryId, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.LanguageId, "Language", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("LanguageId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.LanguageId, "", new { @class = "text-danger" })
                </div>
            </div>

            @*<div class="form-group">
                @Html.LabelFor(model => model.UserId, "UserId", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.DropDownList("UserId", null, htmlAttributes: new { @class = "form-control" })
                    @Html.ValidationMessageFor(model => model.UserId, "", new { @class = "text-danger" })
                </div>
            </div>*@

            <div class="form-group">
                @Html.LabelFor(model => model.Title, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Title, new { htmlAttributes = new { @class = "form-control", id = "tboxTitle" } })
                    @Html.ValidationMessageFor(model => model.Title, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Author, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Author, new { htmlAttributes = new { @class = "form-control", id = "tboxAuthor" } })
                    @Html.ValidationMessageFor(model => model.Author, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.Keywords, htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.Keywords, new { htmlAttributes = new { @class = "form-control", id = "tboxKeywords" } })
                    @Html.ValidationMessageFor(model => model.Keywords, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                @Html.LabelFor(model => model.PublicationYear, "Publication Year", htmlAttributes: new { @class = "control-label col-md-2" })
                <div class="col-md-10">
                    @Html.EditorFor(model => model.PublicationYear, new { htmlAttributes = new { @class = "form-control" } })
                    @Html.ValidationMessageFor(model => model.PublicationYear, "", new { @class = "text-danger" })
                </div>
            </div>

            <div class="form-group">
                <div class="col-md-offset-2 col-md-10">
                    <input type="submit" value="Save" class="btn btn-primary" />
                </div>
            </div>
        @*</div>*@
    }

    </div>

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>

@section Scripts {
    @Scripts.Render("~/bundles/jqueryval")
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.5/js/plugins/piexif.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.5/js/plugins/sortable.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.5/js/plugins/purify.min.js" type="text/javascript"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.11.0/umd/popper.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.5/js/fileinput.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-fileinput/4.4.5/js/locales/LANG.js"></script>

    <script>
        $(document)
            .ready(function () {

                $("#input-id")
                    .fileinput({
                        uploadUrl: "/Upload/UploadFile"
                    })
                    .on('fileuploaded',
                    function (event, data) {
                        console.log(data.response);

                        $("#tboxTitle").val(data.response.Title);
                        $("#tboxFileName").val(data.response.FileName);
                        $("#tboxMIME").val(data.response.MIME);
                        $("#tboxAuthor").val(data.response.Author);
                        $("#tboxKeywords").val(data.response.Keywords);
                    });

                $('.file-caption-main').css("display", "block");
                $('.file-caption').css("max-width", "280px");
                $('.file-input').css("max-width", "601px");
            });
    </script>
}

UDD/UDD.Web/Views/Books/Index.cshtml
@model IEnumerable<UDD.DataAccess.Model.Book>

@{
    ViewBag.Title = "Index";
}

<h2>Books</h2>

<p>
    @if (User.IsInRole("Admin"))
    {
    @Html.ActionLink("Add New Book", "Create")
    }
</p>
<table class="table">
    <tr>
        <th>
            Title
        </th>
        @*<th>
            File Name
        </th>*@
        <th>
            Author
        </th>
        @*<th>
            Keywords
        </th>*@
        <th>
            Publication Year
        </th>
        @*<th>
            MIME
        </th>*@
        <th>
            Category
        </th>
        <th>
            Language
        </th>
        <th>
            Uploaded By
        </th>
        <th>
            Download
        </th>
        <th></th>
    </tr>

@foreach (var item in Model) {
    <tr>
        <td>
            @Html.DisplayFor(modelItem => item.Title)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.FileName)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.Author)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.Keywords)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.PublicationYear)
        </td>
        @*<td>
            @Html.DisplayFor(modelItem => item.MIME)
        </td>*@
        <td>
            @Html.DisplayFor(modelItem => item.Category.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.Language.Name)
        </td>
        <td>
            @Html.DisplayFor(modelItem => item.User.FirstName)
        </td>
        <td>
            @if (item.CanBeDownloaded)
            {
                <a href="@Url.Action("Download", new { filename = item.FileName })">Download</a>
            }
            @if (!User.Identity.IsAuthenticated)
            {
                <a href="@Url.Action("Login", "Auth")">
                    Please login to download
                </a>
            }
        </td>
        <td>
            @if (User.IsInRole("Admin"))
            {
            <span>
            @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
            @Html.ActionLink("Details", "Details", new { id = item.Id }) |
            @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </span>
            }
            else if (User.IsInRole("Subscriber"))
            {
            @Html.ActionLink("Details", "Details", new { id = item.Id })
            }
        </td>
    </tr>
}

</table>